### ISSUE TITLE
Does it work with the file:// protocol?

### ISSUE THREAD

**Issue by andysaini** [zendesk/cross-storage#20]
I understand this will work well with cross origin urls, but can it work with the file:// protocol or is a web server necessary?

**Comment by jden** [comment]
Modern browsers treat file: URLs pretty restrictively and consider them to be different origins in most cases- see for example this note from MDN https://developer.mozilla.org/en-US/docs/Same-origin_policy_for_file%3A_URIs

However, you can use a light-weight development server such as node [http-server](https://www.npmjs.com/package/http-server) or python [SimpleHTTPServer](https://docs.python.org/2/library/simplehttpserver.html) and then access it over http://localhost which will be the same origin.

**Comment by andysaini** [comment]
So it won't work with file:// protocol?

**Comment by jden** [comment]
I don't have a good test case in front of me, but I expect that it would not work. Could you describe your use case and what you're trying to achieve?

**Comment by andysaini** [comment]
I have a multipage app(survey), which needs to store data until an 
internet connection is available to upload it.
The multiple forms in my app are laid out as html files and can be 
navigated via file:// protocol only, but due
to the same origin policy of indexeddb/localstorage, I can't use 
pouchdb, taffyjs etc. Can cross-storage help me?
It says cross-origin requests are supported..

**Comment by danielstjules** [comment]
http://localhost/client.html using file://path/to/hub.html will fail because browsers don't allow it.

file://client.html using http://localhost/hub.html will currently fail because the message.origin is the string "null"
Same with file://client.html using http://localhost/hub.html
I can add support for those two cases above though.

**Comment by danielstjules** [comment]
woops, should read:

> file://client.html using http://localhost/hub.html will fail because message.origin is the string "null"
Same with file://client.html using file://localhost/hub.html

**Comment by danielstjules** [comment]
The two scenarios I highlighted above will work with this quick fix. 

The issue was twofold:
* a message's origin will be the string "null" when the source is a "file://" This is despite `window.location.origin` being "file://"
* The targetOrigin using postMessage must be set to "*" to target a file.

For consistency, you can simply specify an origin of "*" or "file://" in the hub's permissions.
