### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by adeaye** [zendesk/cross-storage#36]
when i use React server and renderToString then the error occured while webpack recompiling my code, it work just fine before i import cross-storage and use  onConnect
![error](https://cloud.githubusercontent.com/assets/16898035/22595626/da8b655c-ea5a-11e6-87c5-095db4c3def0.PNG)

please help, thanks :)

**Comment by baohx2000** [comment]
+1 same here. Guessing it just needs to be defined as a global in the source

**Comment by danielstjules** [comment]
The CrossStorageClient requires that document be defined and won't work in an environment where that isn't the case (e.g. server). I would suggest not creating an instance of CrossStorageClient from any server logic. Keep it to client side lifecycle hooks like componentDidMount. And there used to be a bug where renderToString triggered componentDidMount, so that could be an issue.
